### PR TITLE
Remove unnesessary locale strings

### PR DESCRIPTION
**Pull request by SafeteeWoW**
Using the string constants in "framexml/ptr/GlobalStrings.lua", we can get rid of some locale entries. This will give better translation for some locale, especially if it is not translated on Curseforge yet.

~~~WORK IN PROGRESS.~~~

### CODE REVIEW

**Comment by SafeteeWoW** [comment]
I wonder if you like to implement these changes. If so, I will continue.

**Comment by evil-morfar** [comment]
I would very much like to implement this - the fewer translations needed the better.

**Comment by SafeteeWoW** [comment]
It makes some backward compatibility problems to other modules, so some entries are not completed removed.

**Comment by evil-morfar** [comment]
That's fine - we'll just have to remember to update modules before 2.7 goes live.

**Comment by SafeteeWoW** [comment]
Still WIP

**Comment by SafeteeWoW** [comment]
Done

**Comment by evil-morfar** [comment]
I count 54 fewer translations needed - great job!

**Pull request merged**
