### PR TITLE
Limit update rate to 1 frame.

### PR DESCRIPTION
**Pull request by SafeteeWoW**
+ After the most recent Curseforge report, I realize 0.2s update interval is not good, especially when switching session. Therefore, the update rate is changed to every frame.

### CODE REVIEW

**Comment by evil-morfar** [comment]
The idea behind 0.2 sec was to not have too many Updates in a short period of time. I don't think several responses/lootAcks comes in within a single frame, so this change basically reverts the Update function back to when there wasn't a check.

Also, why should the 0.2s be bad?

**Comment by SafeteeWoW** [comment]
With 0.2s delay, there is a visual delay when switching session with filter enabled? Can you fix that?

**Comment by SafeteeWoW** [comment]
And can you have a look at #122? Since the major bugs have been cleared, can you merge that in the next version?

**Comment by evil-morfar** [comment]
Yes, that's pretty easy. 254471ab38a58169837d6abd632b2e48477eafd2

There's no reason to make the same comment multiple places.

**Pull request closed without merging**
