### PR TITLE
Autopass | Don't pass on transmoggable items

### PR DESCRIPTION
**Pull request by Urtgard**
Implementation for #236 

By default auto pass now does not pass on unkown transmog appearances.
Optional players can choose to not pass on unkown transmog sources.

I did not add any tests because I could not get the busted setup right in a short time.

### CODE REVIEW

**Comment by evil-morfar** [comment]
Awesome! Tests aren't really setup for this scenario, and everything would need to be mocked anyway, so the tests would only really be testing logical/syntax - don't bother with it.

Two comments though:
1. Would anyone really need to have an item that they already has the transmog for? Seems to me it would be simpler to only keep the `autoPassTransmogSource`.
2. I'd prefer if auto passing transmog is enabled by default, so that the common raider doesn't experience any changes simply by updating.

**Comment by evil-morfar** [comment]
3. Since `autoPassTransmogSource` relies on `autoPassTransmog` being `false`, I think it'd be better to disable the option when the latter is `true`. I.e. add `disabled = function() return self.db.profile.autoPassTransmog end`

**Comment by Urtgard** [comment]
Made the two changes based on your comments.

**Comment by evil-morfar** [comment]
Thank you for the contribution - it'll be included in the next update (which will be soonish (tm)).

**Pull request merged**
