### PR TITLE
stack duplicate items in the loot frame.

### PR DESCRIPTION
**Pull request by SafeteeWoW**
+ ~~~Add 'Auto Repeat' feature~~~
+ Add 'Stack Items' feature
  + automatically stack duplicate items in the loot session.
  + This often happens when looting the tokens. For example, three heroic vanquisher leg token drops. If I clicked to response either one, auto repeat my responses to the other two.
  + On by default
+ Add 'Print Response' option
  + Print your response in the chat window
  + Off by default
+ Rename 'autopass' option to "Response options"

### CODE REVIEW

**Comment by evil-morfar** [comment]
This would still let duplicate items show up in the loot frame. This should only show each item once.

**Comment by SafeteeWoW** [comment]
wowscrnshot_102717_113403

**Comment by SafeteeWoW** [comment]
Now items stack. Duplicate items now only show once in the loot frame.

**Comment by SafeteeWoW** [comment]
wowscrnshot_102717_114420

**Comment by SafeteeWoW** [comment]
wowscrnshot_102717_154747

**Comment by SafeteeWoW** [comment]
wowscrnshot_102717_155737

**Comment by evil-morfar** [comment]
The number on the icon seems kinda redundant (?), but otherwise I like it.

**Comment by SafeteeWoW** [comment]
Probably, but the Blizzard UI shows the stack number on the icon too, so I think it makes sense.

**Comment by SafeteeWoW** [comment]
wowscrnshot_102717_194847

**Comment by SafeteeWoW** [comment]
Removed the item count in the item text.

**Comment by evil-morfar** [comment]
That's a nope. I liked the number in the item text, not the icon. It's too hard to see.

**Comment by SafeteeWoW** [comment]
Reverted it. If you think it's good to show the number in the item text, I think I should also keep the number on the icon because this is how Blizzard UI show stacked items.

**Comment by evil-morfar** [comment]
Was there any particular reason you wanted to print responses? It seems a bit redundant to me.
I also don't think there should be an option to stack the items - a lot of people have been asking for this for a long time, they should just stack all the time.

**Comment by SafeteeWoW** [comment]
+ Print response is for people who likes confirmation and to help people realize he clicked the wrong button.
+ Stack items at all times? sure.

**Pull request merged**
