### PR TITLE
Autopass trinket Alternate solution: Hardcode trinket classes

### PR DESCRIPTION
**Pull request by SafeteeWoW**
See Also PR #121 

+ Add developer command:
   + /rc exporttrinketdata to export the class info of trinkets to a window. Copy and paste this code to Util/trinketData.lua
+ Trinket data is hardcoded in Util/TrinketData.lua
+ Add command "/rc trinkettest" or "/rc ttest" for testing.
+ All 26 Antorus trinkets are added to the test.
+ The exports includes all trinkets in all difficulties in all instances in the EJ of the current expansion.
  + No need to hardcode trinkets from earlier expansion. Old trinkets equals to gold for everyone.
+ There is an option ```autoPassTrinket``` to toggle this on/off.
  + Maybe it's possible that people use trinket not for their spec, even if it's half effectiveness.

### CODE REVIEW

**Comment by SafeteeWoW** [comment]
This is ready. Many of the changes are enclosed by @debug

**Comment by evil-morfar** [comment]
Seems fine, not sure it really requires a seperate command for trinket test, but fine. I just didn't want to concentrate on new features with huge bugs going on.

**Comment by SafeteeWoW** [comment]
It shouldn't have much issues and can be easily tested.  The only stuffs released to the end users are autopass trinket options, two more lines in :AutoPassCheck and a trinket data table. Other changes are intended to be used by developers only (enclose by ```@debug```). You can also enclose trinkettest inside debug if you want. It mainly just for my testing purposes.

**Comment by SafeteeWoW** [comment]
format of /rc trinkettest:
/rc trinkettest WARRIOR
/rc trinkettest DEMONHUNTER
etc

**Comment by SafeteeWoW** [comment]
> I just didn't want to concentrate on new features with huge bugs going on.
I know, and this is why I didn't write anything for #88 recently. But compared to that, this feature is not complex, easily tested and unrelated to any other features.

**Comment by evil-morfar** [comment]
This won't go into 2.7.2, but could probably be released before 2.8

**Comment by SafeteeWoW** [comment]
Why? What could be the problem?

**Comment by jokeyrhyme** [comment]
I checked out master, then merged in your PR, and I've killed a boss (The Coven of Shivarra: Heroic) and nothing exploded or crashed :D
No trinkets dropped, so I didn't get to see that part working, however. The rest of the existing functionality in the add-on seems unaffected.

**Comment by SafeteeWoW** [comment]
Can this be merged in the next version?

**Comment by evil-morfar** [comment]
Yes. I wanted to test it in a raid before releasing, and I found no issues.

**Pull request merged**
