### PR TITLE
Fixed ticket #285

### PR DESCRIPTION
**Pull request by SafeteeWoW**
Fix autopass isssue when user uses different localization with the loot master. subType should use user localization instead of master looter localization

### CODE REVIEW

**Comment by SafeteeWoW** [comment]
The issue is detailed described in ticket [#285](https://wow.curseforge.com/projects/rclootcouncil/issues/285)

**Comment by SafeteeWoW** [comment]
Found another issue that autopass doesn't work if user changes game client language after RCLootCouncil installed. Have pushed a commit to fix it.

**Comment by SafeteeWoW** [comment]
Extra Suggestion: You might also consider to use user localized "subType" instead of master looter "subType" in VotingFrame

**Comment by SafeteeWoW** [comment]
Use a new way to fix the problem. Just replace "subType" in the lootTable by the user localized value. 
This will also fix the Voting Frame subType display problem(No relic type display), caused by different localization between master looter and the user.

**Comment by SafeteeWoW** [comment]
Not sure if there are any problem similar to this. We should not assume the loot master uses the same localization with the user.

**Comment by evil-morfar** [comment]
Awesome - great find!

**Pull request merged**
